#!/bin/bash


# Check if all new git commits don't contain forbidden files:
# - .osc
# - _scmsync.obsinfo
# - build.specials.obscpio


set -euo pipefail

echo "Running hook: $(basename $0)"

while read -r old_rev new_rev ref_name; do

    # Skip on branch deletion.
    [[ "$new_rev" =~ ^0+$ ]] && continue

    # Handle branch creation.
    range="${old_rev}..${new_rev}"
    if [[ "$old_rev" =~ ^0+$ ]]; then
        range="$new_rev"
    fi

    # Limit range to only new commits relative to repository history.
    merge_base=$(git merge-base "${new_rev}" $(git for-each-ref --format='%(objectname)') 2>/dev/null | head -n1 || true)
    [ -n "$merge_base" ] && range="${merge_base}..${new_rev}"

    failed=0

    # run check for each new commit
    while read -r commit; do
        # forbid .osc anywhere in the directory structure
        matches=$(git show --pretty="" --name-only --diff-filter=A "${commit}" | grep -E '(^|/)(\.osc|_scmsync\.obsinfo|build\.specials\.obscpio)($|/)' || :)
        if [ -n "${matches}" ]; then
            echo "ERROR: Forbidden file or directory found in commit ${commit}" >&2
            echo "${matches}" >&2
            failed=1
        fi
    done < <(git rev-list "${range}")

    [ "$failed" -eq 1 ] && exit 1
done

exit 0
