#!/usr/bin/python3

import os
import subprocess
import sys

if os.environ.get("PACKAGE_SUBMODULE_BLACKLIST_SKIP", None):
    sys.exit(0)

from osc.git_scm import GitStore
from osc.gitea_api import Git


BLACKLIST_FILE = ".git-workflow/hooks/package-submodule-blacklist.txt"


def check_revision(rev: str) -> bool:
    """
    Check if the specified revision doesn't have any package submodules blacklisted.
    Return True on success, False on failure.
    """
    success = True

    # we always need to instantiate a new GitStore because it uses ref to load the correct _manifest
    store = GitStore(".", ref=rev, check=False)
    git = store._git

    if git.is_bare:
        directories = git.ls_tree(rev)
        directories = [i["path"] for i in directories if i["file_type"] in ("directory", "submodule")]
        package_paths = store.manifest.get_package_paths_bare_git(store.topdir, directories=directories)
    else:
        package_paths = store.manifest.get_package_paths(store.topdir, relative=True)

    submodules = store._git.get_submodules(ref=rev)
    submodule_names = set()
    for key, value in submodules.items():
        if value["path"] not in package_paths:
            continue
        submodule_names.add(os.path.basename(key))

    blacklist_names = set()
    if git.is_bare:
        try:
            data = git._run_git(["cat-file", "blob", f"{rev}:{BLACKLIST_FILE}"], mute_stderr=True)
            blacklist_names = {i.strip() for i in data.splitlines() if i.strip()}
        except subprocess.CalledProcessError:
            # blacklist file doesn't exist -> skip the check, report success
            return success
    else:
        try:
            with open(BLACKLIST_FILE, "r", encoding="utf-8") as f:
                blacklist_names = {i.strip() for i in f.readlines() if i.strip()}
        except FileNotFoundError:
            # blacklist file doesn't exist -> skip the check, report success
            return success

    blacklist_names = {os.path.basename(i) for i in blacklist_names}

    matches = sorted(submodule_names & blacklist_names)
    if matches:
        print(f"Error in commit {rev}")
        print("The following package submodule names are blacklisted: ")
        for name in matches:
            print(f"  - {name}")
        success = False
    return success


def parse_prepush_githook_stdin():
    """
    Returns [(local_ref, local_sha, remote_ref, remote_sha)] from stdin.
    Standard for pre-push hooks.
    """
    result = []
    for line in sys.stdin:
        parts = line.split()
        if len(parts) == 4:
            # pre-push: <local_ref> <local_sha> <remote_ref> <remote_sha>
            local_ref, local_sha, remote_ref, remote_sha = parts
            result.append((local_ref, local_sha, remote_ref, remote_sha))
        else:
            raise RuntimeError(f"Unexpected line in githook stdin: {line}")
    return result


def main():
    git = Git(".")
    seen = set()
    success = True

    # poor man's detection that we're in a pre-receive hook
    is_pre_receive = git.is_bare

    if is_pre_receive:
        rev_list = [(i[0], i[1]) for i in git.parse_githook_stdin()]
    else:
        rev_list = [(i[3], i[1]) for i in parse_prepush_githook_stdin()]

    for old_rev, new_rev in rev_list:
        # we want to enable 'not_all' only in the pre-receive hook
        commits = git.get_commit_range(old_rev, new_rev, not_all=is_pre_receive)
        for sha in commits:
            if sha in seen:
                continue
            success &= check_revision(sha)
            seen.add(sha)

    if not success:
        sys.exit(1)


if __name__ == "__main__":
    main()
